/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.MovimentacaoDAO;
import DTO.MovimentacaoDTO;
import java.sql.SQLException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateus
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrinciapl
     */
    public frmPrincipal() {
        initComponents();
        listaMovimentacao(true);
        if(tblMovimentacao.getRowCount() > 0){
            CarregarCampos(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVeiculos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtaEntrada = new javax.swing.JFormattedTextField();
        lblDataSaida = new javax.swing.JLabel();
        dtaSaida = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimentacao = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        txtHoras = new javax.swing.JFormattedTextField();
        btnCarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        cmbVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veículos Estacionados", "Veículos Não Estacionados" }));
        cmbVeiculos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVeiculosItemStateChanged(evt);
            }
        });

        jLabel1.setText("Selecione a Lista de:");

        lblId.setText("Id:");

        txtId.setEditable(false);

        lblModelo.setText("Modelo:");

        lblPlaca.setText("Placa do Veiculo:");

        jLabel2.setText("Horas:");

        jLabel3.setText("Data Ent:");

        dtaEntrada.setEditable(false);
        dtaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        lblDataSaida.setText("Data Sai:");

        dtaSaida.setEditable(false);
        dtaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel5.setText("R$");

        tblMovimentacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Placa", "Modelo", "Data Entrada", "Data Saida", "Tempo", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblMovimentacao);

        btnCadastrar.setText("Cadatrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSaida.setText("Veiculo Saiu");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        txtHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtHoras.setAutoscrolls(false);

        btnCarregar.setText("Carregar Dados");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(btnCadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSaida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblModelo)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPlaca)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dtaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDataSaida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dtaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataSaida)
                            .addComponent(dtaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarregar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String placa = txtPlaca.getText();
        String modelo = txtModelo.getText();
        Date data_entrada = Date.valueOf(getData());
        Date data_saida = Date.valueOf(getDataPadrao());
        int tempo = Integer.parseInt(txtHoras.getText());
        float valor = Float.parseFloat(txtValor.getText());
        
        MovimentacaoDTO movimentacaoDTO = new MovimentacaoDTO();
        movimentacaoDTO.setPlaca(placa);
        movimentacaoDTO.setModelo(modelo);
        movimentacaoDTO.setData_entrada(data_entrada);
        movimentacaoDTO.setData_saida(data_saida);
        movimentacaoDTO.setTempo(tempo);
        movimentacaoDTO.setValor_pago(valor);
        
        MovimentacaoDAO movimentacaoDAO = new MovimentacaoDAO();
        movimentacaoDAO.cadastrarMovimentacao(movimentacaoDTO);
        
        listaMovimentacao(true);
        
        CarregarCampos(tblMovimentacao.getRowCount()-1);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cmbVeiculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVeiculosItemStateChanged
        if(cmbVeiculos.getSelectedItem().equals("Veículos Estacionados")){
            listaMovimentacao(true);
        }else{
            listaMovimentacao(false);
        }
    }//GEN-LAST:event_cmbVeiculosItemStateChanged

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblMovimentacao.getRowCount() > 0){
            int id = Integer.parseInt(txtId.getText());
            String placa = txtPlaca.getText();
            String modelo = txtModelo.getText();
            Date data_entrada = Date.valueOf(dtaEntrada.getText());
            Date data_saida = Date.valueOf(dtaSaida.getText());
            int tempo = Integer.parseInt(txtHoras.getText());
            float valor = Float.parseFloat(txtValor.getText());


            MovimentacaoDTO movimentacaoDTO = new MovimentacaoDTO();
            movimentacaoDTO.setId(id);
            movimentacaoDTO.setPlaca(placa);
            movimentacaoDTO.setModelo(modelo);
            movimentacaoDTO.setData_entrada(data_entrada);
            movimentacaoDTO.setData_saida(data_saida);
            movimentacaoDTO.setTempo(tempo);
            movimentacaoDTO.setValor_pago(valor);


            MovimentacaoDAO movimentacaoDAO = new MovimentacaoDAO();
            movimentacaoDAO.editarMovimentacao(movimentacaoDTO);

            listaMovimentacao(true);
            if(tblMovimentacao.getRowCount() > 0){
                CarregarCampos(0);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Não ha Veiculos Cadastrados");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        try{
            int row = tblMovimentacao.getSelectedRow();
            CarregarCampos(row);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhum Veiculo Selecionado");
        }
        
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        if(tblMovimentacao.getRowCount() > 0){
            int id = Integer.parseInt(txtId.getText());
            String placa = txtPlaca.getText();
            String modelo = txtModelo.getText();
            Date data_entrada = Date.valueOf(dtaEntrada.getText());
            Date data_saida = Date.valueOf(getData());
            int tempo = Integer.parseInt(txtHoras.getText());
            float valor = Float.parseFloat(txtValor.getText());


            MovimentacaoDTO movimentacaoDTO = new MovimentacaoDTO();
            movimentacaoDTO.setId(id);
            movimentacaoDTO.setPlaca(placa);
            movimentacaoDTO.setModelo(modelo);
            movimentacaoDTO.setData_entrada(data_entrada);
            movimentacaoDTO.setData_saida(data_saida);
            movimentacaoDTO.setTempo(tempo);
            movimentacaoDTO.setValor_pago(valor);


            MovimentacaoDAO movimentacaoDAO = new MovimentacaoDAO();
            movimentacaoDAO.editarMovimentacao(movimentacaoDTO);

            listaMovimentacao(true);
            if(tblMovimentacao.getRowCount() > 0){
                CarregarCampos(0);
            }
            limparCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Não ha Veiculos Cadastrados");
        }
    }//GEN-LAST:event_btnSaidaActionPerformed

            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSaida;
    private javax.swing.JComboBox<String> cmbVeiculos;
    private javax.swing.JFormattedTextField dtaEntrada;
    private javax.swing.JFormattedTextField dtaSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTable tblMovimentacao;
    private javax.swing.JFormattedTextField txtHoras;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    
    private void listaMovimentacao(boolean isAtiva){
        try {
            MovimentacaoDAO movimentacaoDAO = new MovimentacaoDAO();
            
            DefaultTableModel defaultTableModel = (DefaultTableModel) tblMovimentacao.getModel();
            defaultTableModel.setNumRows(0);
            
            ArrayList<MovimentacaoDTO> lista = movimentacaoDAO.pesquisarMovimentacao(isAtiva);
            
            for(int aux = 0; aux < lista.size(); aux++){
                defaultTableModel.addRow(new Object[]{
                    lista.get(aux).getId(),
                    lista.get(aux).getPlaca(),
                    lista.get(aux).getModelo(),
                    lista.get(aux).getData_entrada(),
                    lista.get(aux).getData_saida(),
                    lista.get(aux).getTempo(),
                    lista.get(aux).getValor_pago()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"LIstar Valores"+ e);
        }
    
    }
    
    private void CarregarCampos(int row){
        txtId.setText(tblMovimentacao.getModel().getValueAt(row, 0).toString());
        txtModelo.setText(tblMovimentacao.getModel().getValueAt(row, 1).toString());
        txtPlaca.setText(tblMovimentacao.getModel().getValueAt(row, 2).toString());
        dtaEntrada.setText(tblMovimentacao.getModel().getValueAt(row, 3).toString());
        dtaSaida.setText(tblMovimentacao.getModel().getValueAt(row, 4).toString());
        txtHoras.setText(tblMovimentacao.getModel().getValueAt(row, 5).toString());
        txtValor.setText(tblMovimentacao.getModel().getValueAt(row, 6).toString());
    }
    private void limparCampos(){
        txtId.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        dtaEntrada.setText("");
        dtaSaida.setText("");
        txtHoras.setText("");
        txtValor.setText("");
    }
    
    private String getData(){
        SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date(System.currentTimeMillis());
        String data = formatter.format(date);
        return data;
    }
    
    private String getDataPadrao(){
        String data = "1111-11-11";
        return data;
    }
    
}



